# تحديد نسخة iOS
platform :ios, '15.0'

# استخدام frameworks و modular headers
use_frameworks!
use_modular_headers!

# مسار مشروع Flutter
flutter_application_path = '../'

# تحميل helper الخاص بالـ Flutter
load File.join(flutter_application_path, '.flutter-plugins-dependencies', 'podhelper.rb')

target 'Runner' do
  # تثبيت جميع Flutter Pods
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
