# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods dependency manager
use_frameworks!
use_modular_headers!

# Include the Flutter helper
require File.join(File.dirname(`flutter --version`.strip), '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  # Flutter Pods
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
